export default {
  '1Password': 'onepassword.png',
  AGL: 'AGL.png',
  AIA: 'AIA.png',
  'ALDI Mobile': 'aldi_mobile.png',
  amaysim: 'amaysim.png',
  Amazon: '',
  'Amazon Prime': '',
  'Amazon Web Services': 'AmazonWebServices.png',
  'Ambulance Victoria': 'ambulancevictoria.png',
  'Angle Auto Finance': 'AngleAutoFinance.png',
  'ANMF (Vic Branch)': 'ANMF.png',
  Apple: 'apple.png',
  Audible: 'audible.png',
  'Aussie Broadband': 'Aussie-Broadband.png',
  'Australian Services Union': 'AustralianServicesUnion.png',
  'Australian Tax Office': 'AustralianTaxOffice.png',
  'Australian Unity': 'AustralianUnity.png',
  Belong: 'Belong.png',
  Binge: 'Binge.png',
  Bingle: 'Bingle.png',
  Bitwarden: 'bitwarden.png',
  'Body Fit Training': 'BodyFitTraining.png',
  'Boost Mobile': 'boostmobile.png',
  Canva: 'Canva.png',
  'CBHS Health Fund': 'CBHSHealth.png',
  Centrelink: '',
  CGU: 'CGU.png',
  'Circles Life': 'CircleLife.png',
  ClassPass: 'ClassPass.png',
  'Club Lime': 'ClubLime.png',
  'Commonwealth Bank': 'CommonwealthBank.png',
  'Compassion Australia': 'CompassionAustralia.png',
  CPSU: 'CPSU.png',
  'Credit Corp': 'CreditCorpGroup.png',
  DEFT: 'DEFT.png',
  DentiCare: 'Denticare.png',
  'Department for Infrastures and Transport':
    'DepartmentforInfrastructureandTransport.png',
  'Department of Transport WA': '',
  'Derrimut 27:7 Gym': 'DerrimutGym.png',
  Discord: 'Discord.png',
  'Disney+': 'Disney+.png',
  Dropbox: 'Dropbox.png',
  Dropout: 'Dropout.png',
  EnergyAustralia: 'EnergyAustralia.png',
  'Everyday Mobile': 'everydaymobile.png',
  'Everyday Rewards': 'EverydayRewards.png',
  Exetel: 'Exetel.png',
  EzyReg: 'EzyReg.png',
  Felix: 'Felix.png',
  'Fernwood Fitness': 'FitnessFernwood.png',
  'Fines Victoria': 'FinesVictoria.png',
  'Firstmac/Loans.com.au / MCCA': 'FirstmacLoansMCCA.png',
  'Fitness Cartel': 'FitnessCartel.png',
  'Fitness First': 'FitnessFirst.png',
  Foxtel: 'Foxtel.png',
  Genesis: 'Genesis.png',
  GIO: 'GIO.png',
  GitHub: 'GitHub.png',
  GLOFOX: 'Glofox.png',
  GMHBA: 'GMHBA.png',
  'Google Nest': 'GoogleNest.png',
  'Google One': 'googleone.png',
  'Google Play': 'GooglePlay.png',
  'Google Workspace': 'GoogleWorkspace.png',
  'Healthy Pets Plus': 'HealthyPetsPlus.png',
  humm: 'humm.png',
  ING: 'ING.png',
  Internode: 'Internode.png',
  'JB Hi-Fi': 'JBHIFI.png',
  'Jetts Fitness': 'JetssFitnessFreedom.png',
  'Kayo Sports': 'Kayo_SPORTS.png',
  'Kayo Sports/Bingo / Flas': 'KayoSports_Binge_Flash.png',
  'Kogan Mobile': 'koganmobile.png',
  Latitude: 'Latitude.png',
  Linkt: 'Linkt.png',
  'LMCT Plus': 'LMCTPlus.png',
  'Macquarie Bank': 'MacquarieBank.png',
  Mate: 'Mate.png',
  'Mazda Finance': 'MazdaFinance.png',
  Mindbody: 'Mindbody.png',
  Money3: 'M3.png',
  'Moose Mobile': 'MooseMobile.png',
  Netflix: 'netflix.png',
  'News Corp Australia': 'NewsCorpAustralia.png',
  Nine: 'Nine.png',
  'One Pass': 'onepassword.png',
  OpenAI: 'OPENAI.png',
  Optus: 'optus.png',
  'Origin Broadband': 'originbroadband.png',
  'Origin Energy': 'OriginEnergy.png',
  OurMoneyMarket: 'Ourmonery_market.png',
  'OVO Energy': 'OVOEnergy.png',
  Paddle: 'Paddie.png',
  Pearler: 'Pearler.png',
  'Planet Fitness': 'PlanetFitness.png',
  Plenti: 'Plenti.png',
  Plex: '',
  'Plus Fitness': 'PlusFitness.png',
  'PowerTorque Finance': 'PowerTorque.png',
  Proton: 'Proton.png',
  QBE: 'QBE.png',
  "QNMU Queensland Nurses & Midwive's Union": 'QNMU.png',
  'RAC WA': 'RAC.png',
  Racq: 'RACQ.png',
  RACT: 'RACT.png',
  'Red Energy': 'RedEnergy.png',
  'Revenue NSW': 'RevenueNSW.png',
  'Revo Fitness': 'RevoFitness.png',
  Ring: 'Ring.png',
  'Service NSW': 'ServiceNSW.png',
  Shannons: 'Shannons.png',
  'Snap Fitness': 'SnapFitness25-7.png',
  Soundcloud: 'Soundcloud.png',
  'South East Water': 'SouthEastWater.png',
  SpinTel: 'Spintel.png',
  Spotify: 'spotify.png',
  Squarespace: 'Squarespace.png',
  'St. George Bank': '',
  Stan: 'stan.png',
  Starlink: 'Starlink.png',
  'State Penalties Enforcement Registry Queensland': 'StatePenalties.png',
  'Suncorp Insurance': 'Suncorp.png',
  Superloop: 'Superloop.png',
  Synergy: 'Synergy.png',
  'Tangerine Telecom': 'TangerineTelecoms.png',
  'Teachers Health / Nurse & Midwives Health': 'TeachersHealth.png',
  Telstra: 'telstra.png',
  Tesla: 'Tesla.png',
  'The New York Times': 'TheNewYorkTimes.png',
  'Toyota Finance': 'ToyotaFinancialServices.png',
  Twitch: 'Twitch.png',
  Uber: 'Uber.png',
  Vanguard: 'Vanguard.png',
  Vaya: 'Vaya.png',
  VetPay: 'VetPay.png',
  'Virgin Active': 'VirginActive.png',
  'Virgin Money': 'VirginMoney.png',
  'Volkswagen Financial Services Australia': 'Volkswagen.png',
  'Water Corporation': 'WaterCorporation.png',
  Wisr: 'WISR.png',
  Woolworths: 'Woolworth.png',
  'World Gym': 'WorldGym.png',
  'Yarra Valley Water': 'YarraValey.png',
  Youtube: 'youtube.png',
  'Zai Payments Australia': 'ZaiPaymentAustralia.png',
  'Zap Fitness': 'ZapFitness.png',
  Zip: 'zip.png',
}
